# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MqttMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MqttMessage.proto',
  package='com.hashmapinc.tempus.edge.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x11MqttMessage.proto\x12 com.hashmapinc.tempus.edge.proto\"\x90\x01\n\x0bMqttMessage\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12>\n\x03qos\x18\x03 \x01(\x0e\x32\x31.com.hashmapinc.tempus.edge.proto.MqttMessage.QoS\"!\n\x03QoS\x12\x08\n\x04ZERO\x10\x00\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02\x42\"Z com/hashmapinc/tempus/edge/protob\x06proto3')
)



_MQTTMESSAGE_QOS = _descriptor.EnumDescriptor(
  name='QoS',
  full_name='com.hashmapinc.tempus.edge.proto.MqttMessage.QoS',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ZERO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TWO', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=167,
  serialized_end=200,
)
_sym_db.RegisterEnumDescriptor(_MQTTMESSAGE_QOS)


_MQTTMESSAGE = _descriptor.Descriptor(
  name='MqttMessage',
  full_name='com.hashmapinc.tempus.edge.proto.MqttMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='com.hashmapinc.tempus.edge.proto.MqttMessage.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='com.hashmapinc.tempus.edge.proto.MqttMessage.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qos', full_name='com.hashmapinc.tempus.edge.proto.MqttMessage.qos', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MQTTMESSAGE_QOS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=200,
)

_MQTTMESSAGE.fields_by_name['qos'].enum_type = _MQTTMESSAGE_QOS
_MQTTMESSAGE_QOS.containing_type = _MQTTMESSAGE
DESCRIPTOR.message_types_by_name['MqttMessage'] = _MQTTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MqttMessage = _reflection.GeneratedProtocolMessageType('MqttMessage', (_message.Message,), dict(
  DESCRIPTOR = _MQTTMESSAGE,
  __module__ = 'MqttMessage_pb2'
  # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.MqttMessage)
  ))
_sym_db.RegisterMessage(MqttMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z com/hashmapinc/tempus/edge/proto'))
# @@protoc_insertion_point(module_scope)
