# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MqttConfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MqttConfig.proto',
  package='com.hashmapinc.tempus.edge.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x10MqttConfig.proto\x12 com.hashmapinc.tempus.edge.proto\"\xc0\x04\n\nMqttConfig\x12J\n\rsubscriptions\x18\x01 \x03(\x0b\x32\x33.com.hashmapinc.tempus.edge.proto.MqttConfig.SubPub\x12G\n\npublishers\x18\x02 \x03(\x0b\x32\x33.com.hashmapinc.tempus.edge.proto.MqttConfig.SubPub\x12\x43\n\x06\x62roker\x18\x03 \x01(\x0b\x32\x33.com.hashmapinc.tempus.edge.proto.MqttConfig.Broker\x12P\n\rsecurity_type\x18\x04 \x01(\x0e\x32\x39.com.hashmapinc.tempus.edge.proto.MqttConfig.SecurityType\x12?\n\x04user\x18\x05 \x01(\x0b\x32\x31.com.hashmapinc.tempus.edge.proto.MqttConfig.User\x12\x13\n\x0bmax_retries\x18\x06 \x01(\r\x12\x13\n\x0bretry_delay\x18\x07 \x01(\x04\x1a$\n\x06SubPub\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0b\n\x03qos\x18\x02 \x01(\x05\x1a$\n\x06\x42roker\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x1a*\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"#\n\x0cSecurityType\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05TOKEN\x10\x01\x42\"Z com/hashmapinc/tempus/edge/protob\x06proto3')
)



_MQTTCONFIG_SECURITYTYPE = _descriptor.EnumDescriptor(
  name='SecurityType',
  full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.SecurityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOKEN', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=596,
  serialized_end=631,
)
_sym_db.RegisterEnumDescriptor(_MQTTCONFIG_SECURITYTYPE)


_MQTTCONFIG_SUBPUB = _descriptor.Descriptor(
  name='SubPub',
  full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.SubPub',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.SubPub.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qos', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.SubPub.qos', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=512,
)

_MQTTCONFIG_BROKER = _descriptor.Descriptor(
  name='Broker',
  full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.Broker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.Broker.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.Broker.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=550,
)

_MQTTCONFIG_USER = _descriptor.Descriptor(
  name='User',
  full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.User.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=594,
)

_MQTTCONFIG = _descriptor.Descriptor(
  name='MqttConfig',
  full_name='com.hashmapinc.tempus.edge.proto.MqttConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscriptions', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.subscriptions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publishers', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.publishers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='broker', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.broker', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='security_type', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.security_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.user', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_retries', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.max_retries', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retry_delay', full_name='com.hashmapinc.tempus.edge.proto.MqttConfig.retry_delay', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MQTTCONFIG_SUBPUB, _MQTTCONFIG_BROKER, _MQTTCONFIG_USER, ],
  enum_types=[
    _MQTTCONFIG_SECURITYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=631,
)

_MQTTCONFIG_SUBPUB.containing_type = _MQTTCONFIG
_MQTTCONFIG_BROKER.containing_type = _MQTTCONFIG
_MQTTCONFIG_USER.containing_type = _MQTTCONFIG
_MQTTCONFIG.fields_by_name['subscriptions'].message_type = _MQTTCONFIG_SUBPUB
_MQTTCONFIG.fields_by_name['publishers'].message_type = _MQTTCONFIG_SUBPUB
_MQTTCONFIG.fields_by_name['broker'].message_type = _MQTTCONFIG_BROKER
_MQTTCONFIG.fields_by_name['security_type'].enum_type = _MQTTCONFIG_SECURITYTYPE
_MQTTCONFIG.fields_by_name['user'].message_type = _MQTTCONFIG_USER
_MQTTCONFIG_SECURITYTYPE.containing_type = _MQTTCONFIG
DESCRIPTOR.message_types_by_name['MqttConfig'] = _MQTTCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MqttConfig = _reflection.GeneratedProtocolMessageType('MqttConfig', (_message.Message,), dict(

  SubPub = _reflection.GeneratedProtocolMessageType('SubPub', (_message.Message,), dict(
    DESCRIPTOR = _MQTTCONFIG_SUBPUB,
    __module__ = 'MqttConfig_pb2'
    # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.MqttConfig.SubPub)
    ))
  ,

  Broker = _reflection.GeneratedProtocolMessageType('Broker', (_message.Message,), dict(
    DESCRIPTOR = _MQTTCONFIG_BROKER,
    __module__ = 'MqttConfig_pb2'
    # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.MqttConfig.Broker)
    ))
  ,

  User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
    DESCRIPTOR = _MQTTCONFIG_USER,
    __module__ = 'MqttConfig_pb2'
    # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.MqttConfig.User)
    ))
  ,
  DESCRIPTOR = _MQTTCONFIG,
  __module__ = 'MqttConfig_pb2'
  # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.MqttConfig)
  ))
_sym_db.RegisterMessage(MqttConfig)
_sym_db.RegisterMessage(MqttConfig.SubPub)
_sym_db.RegisterMessage(MqttConfig.Broker)
_sym_db.RegisterMessage(MqttConfig.User)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z com/hashmapinc/tempus/edge/proto'))
# @@protoc_insertion_point(module_scope)
