# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpcConfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='OpcConfig.proto',
  package='com.hashmapinc.tempus.edge.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0fOpcConfig.proto\x12 com.hashmapinc.tempus.edge.proto\"\xbe\x07\n\tOpcConfig\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12O\n\rsecurity_type\x18\x02 \x01(\x0e\x32\x38.com.hashmapinc.tempus.edge.proto.OpcConfig.SecurityType\x12K\n\x0btag_filters\x18\x03 \x01(\x0b\x32\x36.com.hashmapinc.tempus.edge.proto.OpcConfig.TagFilters\x12\x45\n\x08tag_root\x18\x04 \x01(\x0b\x32\x33.com.hashmapinc.tempus.edge.proto.OpcConfig.OpcNode\x12J\n\x0b\x64\x65vice_maps\x18\x05 \x03(\x0b\x32\x35.com.hashmapinc.tempus.edge.proto.OpcConfig.DeviceMap\x12G\n\x04subs\x18\x06 \x01(\x0b\x32\x39.com.hashmapinc.tempus.edge.proto.OpcConfig.Subscriptions\x12\x18\n\x10subs_update_freq\x18\x07 \x01(\r\x12\x17\n\x0f\x63lient_identity\x18\x08 \x01(\t\x12\x17\n\x0f\x63lient_password\x18\t \x01(\t\x12\x13\n\x0bmax_retries\x18\n \x01(\r\x12\x13\n\x0bretry_delay\x18\x0b \x01(\x04\x1a\x32\n\nTagFilters\x12\x11\n\twhitelist\x18\x01 \x03(\t\x12\x11\n\tblacklist\x18\x02 \x03(\t\x1a(\n\x07OpcNode\x12\x11\n\tnamespace\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\x1a\x31\n\tDeviceMap\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x02 \x01(\t\x1a\xce\x01\n\rSubscriptions\x12U\n\x05nodes\x18\x01 \x03(\x0b\x32\x46.com.hashmapinc.tempus.edge.proto.OpcConfig.Subscriptions.Subscription\x1a\x66\n\x0cSubscription\x12\x41\n\x04node\x18\x01 \x01(\x0b\x32\x33.com.hashmapinc.tempus.edge.proto.OpcConfig.OpcNode\x12\x13\n\x0b\x64\x65vice_name\x18\x02 \x01(\t\"M\n\x0cSecurityType\x12\x08\n\x04NONE\x10\x00\x12\x11\n\rBASIC128RSA15\x10\x01\x12\x0c\n\x08\x42\x41SIC256\x10\x02\x12\x12\n\x0e\x42\x41SIC256SHA256\x10\x03\x42\"Z com/hashmapinc/tempus/edge/protob\x06proto3')
)



_OPCCONFIG_SECURITYTYPE = _descriptor.EnumDescriptor(
  name='SecurityType',
  full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.SecurityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASIC128RSA15', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASIC256', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASIC256SHA256', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=935,
  serialized_end=1012,
)
_sym_db.RegisterEnumDescriptor(_OPCCONFIG_SECURITYTYPE)


_OPCCONFIG_TAGFILTERS = _descriptor.Descriptor(
  name='TagFilters',
  full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.TagFilters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='whitelist', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.TagFilters.whitelist', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blacklist', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.TagFilters.blacklist', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=631,
)

_OPCCONFIG_OPCNODE = _descriptor.Descriptor(
  name='OpcNode',
  full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.OpcNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.OpcNode.namespace', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.OpcNode.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=633,
  serialized_end=673,
)

_OPCCONFIG_DEVICEMAP = _descriptor.Descriptor(
  name='DeviceMap',
  full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.DeviceMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pattern', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.DeviceMap.pattern', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_name', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.DeviceMap.device_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=675,
  serialized_end=724,
)

_OPCCONFIG_SUBSCRIPTIONS_SUBSCRIPTION = _descriptor.Descriptor(
  name='Subscription',
  full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.Subscriptions.Subscription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.Subscriptions.Subscription.node', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_name', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.Subscriptions.Subscription.device_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=831,
  serialized_end=933,
)

_OPCCONFIG_SUBSCRIPTIONS = _descriptor.Descriptor(
  name='Subscriptions',
  full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.Subscriptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.Subscriptions.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OPCCONFIG_SUBSCRIPTIONS_SUBSCRIPTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=727,
  serialized_end=933,
)

_OPCCONFIG = _descriptor.Descriptor(
  name='OpcConfig',
  full_name='com.hashmapinc.tempus.edge.proto.OpcConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.endpoint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='security_type', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.security_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag_filters', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.tag_filters', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag_root', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.tag_root', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_maps', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.device_maps', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subs', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.subs', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subs_update_freq', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.subs_update_freq', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_identity', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.client_identity', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_password', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.client_password', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_retries', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.max_retries', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retry_delay', full_name='com.hashmapinc.tempus.edge.proto.OpcConfig.retry_delay', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OPCCONFIG_TAGFILTERS, _OPCCONFIG_OPCNODE, _OPCCONFIG_DEVICEMAP, _OPCCONFIG_SUBSCRIPTIONS, ],
  enum_types=[
    _OPCCONFIG_SECURITYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=1012,
)

_OPCCONFIG_TAGFILTERS.containing_type = _OPCCONFIG
_OPCCONFIG_OPCNODE.containing_type = _OPCCONFIG
_OPCCONFIG_DEVICEMAP.containing_type = _OPCCONFIG
_OPCCONFIG_SUBSCRIPTIONS_SUBSCRIPTION.fields_by_name['node'].message_type = _OPCCONFIG_OPCNODE
_OPCCONFIG_SUBSCRIPTIONS_SUBSCRIPTION.containing_type = _OPCCONFIG_SUBSCRIPTIONS
_OPCCONFIG_SUBSCRIPTIONS.fields_by_name['nodes'].message_type = _OPCCONFIG_SUBSCRIPTIONS_SUBSCRIPTION
_OPCCONFIG_SUBSCRIPTIONS.containing_type = _OPCCONFIG
_OPCCONFIG.fields_by_name['security_type'].enum_type = _OPCCONFIG_SECURITYTYPE
_OPCCONFIG.fields_by_name['tag_filters'].message_type = _OPCCONFIG_TAGFILTERS
_OPCCONFIG.fields_by_name['tag_root'].message_type = _OPCCONFIG_OPCNODE
_OPCCONFIG.fields_by_name['device_maps'].message_type = _OPCCONFIG_DEVICEMAP
_OPCCONFIG.fields_by_name['subs'].message_type = _OPCCONFIG_SUBSCRIPTIONS
_OPCCONFIG_SECURITYTYPE.containing_type = _OPCCONFIG
DESCRIPTOR.message_types_by_name['OpcConfig'] = _OPCCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpcConfig = _reflection.GeneratedProtocolMessageType('OpcConfig', (_message.Message,), dict(

  TagFilters = _reflection.GeneratedProtocolMessageType('TagFilters', (_message.Message,), dict(
    DESCRIPTOR = _OPCCONFIG_TAGFILTERS,
    __module__ = 'OpcConfig_pb2'
    # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.OpcConfig.TagFilters)
    ))
  ,

  OpcNode = _reflection.GeneratedProtocolMessageType('OpcNode', (_message.Message,), dict(
    DESCRIPTOR = _OPCCONFIG_OPCNODE,
    __module__ = 'OpcConfig_pb2'
    # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.OpcConfig.OpcNode)
    ))
  ,

  DeviceMap = _reflection.GeneratedProtocolMessageType('DeviceMap', (_message.Message,), dict(
    DESCRIPTOR = _OPCCONFIG_DEVICEMAP,
    __module__ = 'OpcConfig_pb2'
    # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.OpcConfig.DeviceMap)
    ))
  ,

  Subscriptions = _reflection.GeneratedProtocolMessageType('Subscriptions', (_message.Message,), dict(

    Subscription = _reflection.GeneratedProtocolMessageType('Subscription', (_message.Message,), dict(
      DESCRIPTOR = _OPCCONFIG_SUBSCRIPTIONS_SUBSCRIPTION,
      __module__ = 'OpcConfig_pb2'
      # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.OpcConfig.Subscriptions.Subscription)
      ))
    ,
    DESCRIPTOR = _OPCCONFIG_SUBSCRIPTIONS,
    __module__ = 'OpcConfig_pb2'
    # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.OpcConfig.Subscriptions)
    ))
  ,
  DESCRIPTOR = _OPCCONFIG,
  __module__ = 'OpcConfig_pb2'
  # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.OpcConfig)
  ))
_sym_db.RegisterMessage(OpcConfig)
_sym_db.RegisterMessage(OpcConfig.TagFilters)
_sym_db.RegisterMessage(OpcConfig.OpcNode)
_sym_db.RegisterMessage(OpcConfig.DeviceMap)
_sym_db.RegisterMessage(OpcConfig.Subscriptions)
_sym_db.RegisterMessage(OpcConfig.Subscriptions.Subscription)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z com/hashmapinc/tempus/edge/proto'))
# @@protoc_insertion_point(module_scope)
