# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpcMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import OpcConfig_pb2 as OpcConfig__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='OpcMessage.proto',
  package='com.hashmapinc.tempus.edge.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x10OpcMessage.proto\x12 com.hashmapinc.tempus.edge.proto\x1a\x0fOpcConfig.proto\"\xad\x02\n\nOpcMessage\x12\x41\n\x04node\x18\x01 \x01(\x0b\x32\x33.com.hashmapinc.tempus.edge.proto.OpcConfig.OpcNode\x12\x13\n\x0b\x64\x65vice_name\x18\x02 \x01(\t\x12\x17\n\x0fsource_datetime\x18\x03 \x01(\t\x12\x17\n\x0fserver_datetime\x18\x04 \x01(\t\x12\x16\n\x0cvalue_string\x18\x05 \x01(\tH\x00\x12\x15\n\x0bvalue_int32\x18\x06 \x01(\x05H\x00\x12\x15\n\x0bvalue_int64\x18\x07 \x01(\x03H\x00\x12\x15\n\x0bvalue_float\x18\x08 \x01(\x02H\x00\x12\x16\n\x0cvalue_double\x18\t \x01(\x01H\x00\x12\x17\n\rvalue_boolean\x18\n \x01(\x08H\x00\x42\x07\n\x05valueB\"Z com/hashmapinc/tempus/edge/protob\x06proto3')
  ,
  dependencies=[OpcConfig__pb2.DESCRIPTOR,])




_OPCMESSAGE = _descriptor.Descriptor(
  name='OpcMessage',
  full_name='com.hashmapinc.tempus.edge.proto.OpcMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='com.hashmapinc.tempus.edge.proto.OpcMessage.node', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_name', full_name='com.hashmapinc.tempus.edge.proto.OpcMessage.device_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_datetime', full_name='com.hashmapinc.tempus.edge.proto.OpcMessage.source_datetime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_datetime', full_name='com.hashmapinc.tempus.edge.proto.OpcMessage.server_datetime', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_string', full_name='com.hashmapinc.tempus.edge.proto.OpcMessage.value_string', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_int32', full_name='com.hashmapinc.tempus.edge.proto.OpcMessage.value_int32', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_int64', full_name='com.hashmapinc.tempus.edge.proto.OpcMessage.value_int64', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_float', full_name='com.hashmapinc.tempus.edge.proto.OpcMessage.value_float', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_double', full_name='com.hashmapinc.tempus.edge.proto.OpcMessage.value_double', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_boolean', full_name='com.hashmapinc.tempus.edge.proto.OpcMessage.value_boolean', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='com.hashmapinc.tempus.edge.proto.OpcMessage.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=72,
  serialized_end=373,
)

_OPCMESSAGE.fields_by_name['node'].message_type = OpcConfig__pb2._OPCCONFIG_OPCNODE
_OPCMESSAGE.oneofs_by_name['value'].fields.append(
  _OPCMESSAGE.fields_by_name['value_string'])
_OPCMESSAGE.fields_by_name['value_string'].containing_oneof = _OPCMESSAGE.oneofs_by_name['value']
_OPCMESSAGE.oneofs_by_name['value'].fields.append(
  _OPCMESSAGE.fields_by_name['value_int32'])
_OPCMESSAGE.fields_by_name['value_int32'].containing_oneof = _OPCMESSAGE.oneofs_by_name['value']
_OPCMESSAGE.oneofs_by_name['value'].fields.append(
  _OPCMESSAGE.fields_by_name['value_int64'])
_OPCMESSAGE.fields_by_name['value_int64'].containing_oneof = _OPCMESSAGE.oneofs_by_name['value']
_OPCMESSAGE.oneofs_by_name['value'].fields.append(
  _OPCMESSAGE.fields_by_name['value_float'])
_OPCMESSAGE.fields_by_name['value_float'].containing_oneof = _OPCMESSAGE.oneofs_by_name['value']
_OPCMESSAGE.oneofs_by_name['value'].fields.append(
  _OPCMESSAGE.fields_by_name['value_double'])
_OPCMESSAGE.fields_by_name['value_double'].containing_oneof = _OPCMESSAGE.oneofs_by_name['value']
_OPCMESSAGE.oneofs_by_name['value'].fields.append(
  _OPCMESSAGE.fields_by_name['value_boolean'])
_OPCMESSAGE.fields_by_name['value_boolean'].containing_oneof = _OPCMESSAGE.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['OpcMessage'] = _OPCMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpcMessage = _reflection.GeneratedProtocolMessageType('OpcMessage', (_message.Message,), dict(
  DESCRIPTOR = _OPCMESSAGE,
  __module__ = 'OpcMessage_pb2'
  # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.OpcMessage)
  ))
_sym_db.RegisterMessage(OpcMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z com/hashmapinc/tempus/edge/proto'))
# @@protoc_insertion_point(module_scope)
