# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TrackConfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import TrackMetadata_pb2 as TrackMetadata__pb2
from . import MqttConfig_pb2 as MqttConfig__pb2
from . import OpcConfig_pb2 as OpcConfig__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TrackConfig.proto',
  package='com.hashmapinc.tempus.edge.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x11TrackConfig.proto\x12 com.hashmapinc.tempus.edge.proto\x1a\x13TrackMetadata.proto\x1a\x10MqttConfig.proto\x1a\x0fOpcConfig.proto\"\xda\x01\n\x0bTrackConfig\x12G\n\x0etrack_metadata\x18\x01 \x01(\x0b\x32/.com.hashmapinc.tempus.edge.proto.TrackMetadata\x12\x41\n\x0bmqtt_config\x18\x02 \x01(\x0b\x32,.com.hashmapinc.tempus.edge.proto.MqttConfig\x12?\n\nopc_config\x18\x03 \x01(\x0b\x32+.com.hashmapinc.tempus.edge.proto.OpcConfigB\"Z com/hashmapinc/tempus/edge/protob\x06proto3')
  ,
  dependencies=[TrackMetadata__pb2.DESCRIPTOR,MqttConfig__pb2.DESCRIPTOR,OpcConfig__pb2.DESCRIPTOR,])




_TRACKCONFIG = _descriptor.Descriptor(
  name='TrackConfig',
  full_name='com.hashmapinc.tempus.edge.proto.TrackConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='track_metadata', full_name='com.hashmapinc.tempus.edge.proto.TrackConfig.track_metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mqtt_config', full_name='com.hashmapinc.tempus.edge.proto.TrackConfig.mqtt_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opc_config', full_name='com.hashmapinc.tempus.edge.proto.TrackConfig.opc_config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=330,
)

_TRACKCONFIG.fields_by_name['track_metadata'].message_type = TrackMetadata__pb2._TRACKMETADATA
_TRACKCONFIG.fields_by_name['mqtt_config'].message_type = MqttConfig__pb2._MQTTCONFIG
_TRACKCONFIG.fields_by_name['opc_config'].message_type = OpcConfig__pb2._OPCCONFIG
DESCRIPTOR.message_types_by_name['TrackConfig'] = _TRACKCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrackConfig = _reflection.GeneratedProtocolMessageType('TrackConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRACKCONFIG,
  __module__ = 'TrackConfig_pb2'
  # @@protoc_insertion_point(class_scope:com.hashmapinc.tempus.edge.proto.TrackConfig)
  ))
_sym_db.RegisterMessage(TrackConfig)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z com/hashmapinc/tempus/edge/proto'))
# @@protoc_insertion_point(module_scope)
